[project]
name = "veilpay"
description = "Private USDCx transfers on Stacks using Zero-Knowledge proofs"
authors = ["Carlos Israel Jim√©nez"]
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.veilpay]
path = "veilpay.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2
